spring:
  application:
    name: Question Check API
  datasource:
    url: "jdbc:postgresql://localhost:25432/my_store_db?currentSchema=public"
    username: "my_store"
    password: "123"
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /api
  port: 8082



